### PR TITLE
Don't trigger "Save webpage" when save/edit shortcut keys are pressed

### PR DESCRIPTION
**Pull request by LanjianNUll**
When saving with a shortcut key, multiple operations will cause the save webpage to pop up.

### CODE REVIEW

**Comment by plibither8** [comment]
Hi :wave:!

Thanks a lot for your PR. It seems that you have moved the `e.preventDefault()` command so as to trigger whenever that keyCode combination is pressed, which is great (never thought of this issue :D).

I guess the change made here: https://github.com/plibither8/markdown-new-tab/pull/23/files#diff-99a85c3932c0670278158f38d818e0efR582 at line 582 is unnecessary, don't you think?

Thanks again :)

**Comment by LanjianNUll** [comment]
> Hi 👋!
> 
> Thanks a lot for your PR. It seems that you have moved the `e.preventDefault()` command so as to trigger whenever that keyCode combination is pressed, which is great (never thought of this issue :D).
> 
> I guess the change made here: https://github.com/plibither8/markdown-new-tab/pull/23/files#diff-99a85c3932c0670278158f38d818e0efR582 at line 582 is unnecessary, don't you think?
> 
> Thanks again :)

Sorry, I have been replying to you for so long. Because my computer is a window operating system, I don't quite understand the browser behavior on my Mac. On this point, I will go to verify, through my colleague or friend's mac.

**Comment by plibither8** [comment]
Hey @LanjianNUll, any updated? 🙂

**Comment by LanjianNUll** [comment]
> Hey @LanjianNUll, any updated?

no

**Comment by LanjianNUll** [comment]
> Hey @LanjianNUll, any updated?

Good morning
, I don't have any updates yet.

**Pull request closed without merging**
